# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        LSI\MarketBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_PART:        ROLE_PART
        ROLE_MAIRIE:      [ ROLE_MAIRIE, ROLE_PART ]
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                provider:     main
                check_path: fos_user_security_check
                default_target_path: /market/monespace
            logout:
                path: fos_user_security_logout
                target: /market/login
            remember_me:
                secret:     '%secret%'
            #logout: true
            anonymous: true
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/administre/, role: ROLE_PART }
        - { path: ^/mairie/, role: ROLE_MAIRIE }
        - { path: ^/superadmin/, role: ROLE_ADMIN }
